version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: /node_modules/.bin/nodemon server.js
    volumes:
      - ./server/
      - /node_modules
    ports:
      - "3002:3002"
    networks:
      - app-network

  client:
    build:
      context: ./
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./:/
      - /node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
